// All keyword arrays

exports.jobKeywords = [
  'jobs',
  'job openings',
  'recruitment',
  'hiring',
  'career',
  'vacancy',
  'vacancies',
  'walk-in interview',
  'interview schedule',
  'job notification',
  'exam notification',
  'employment',
  'employment news',
  'sarkari naukri',
  'private jobs',
  'fresher jobs',
  'internship',
  'apprentice',
  'job drive',
  'campus placement',
  'positions available',
  'now hiring',
  'job fair',
  'employment drive',
];

exports.companyNames = [
  'tcs',
  'infosys',
  'wipro',
  'hcl',
  'tech mahindra',
  'accenture',
  'capgemini',
  'cognizant',
  'hiring by',
  'mass hiring',
  'layoffs',
];

exports.stateGovtKeywords = [
  'tnpsc',
  'mpsc',
  'uppsc',
  'bpsc',
  'apsc',
  'kpsc',
  'wbpsc',
  'state govt',
  'state government job',
  'psc recruitment',
  'police constable',
  'teacher recruitment',
  'group d',
  'group c',
  'gramin',
  'municipal recruitment',
  'state exam',
];

exports.centralGovtKeywords = [
  'upsc',
  'ssc',
  'rrb',
  'railway recruitment',
  'defence job',
  'army recruitment',
  'navy recruitment',
  'air force recruitment',
  'ibps',
  'sbi recruitment',
  'public sector undertaking',
  'psu recruitment',
  'ntpc recruitment',
  'bpsc',
  'drdo recruitment',
  'isro recruitment',
  'nhpc',
  'government of india',
  'central government job',
  'ministry of',
  'group a',
  'group b',
  'group c',
  'group d',
  'central govt jobs',
  'union government',
  'uidai',
];
