export const messages = [
  {
    id: 1,
    sender: 'Infosys Careers',
    date: 'July 12, 9:00 AM',
    subject: 'You’ve been shortlisted for Associate Software Engineer',
    preview: 'Congratulations! You have been shortlisted for the interview round at Infosys...',
    type: 'Interview',
    isUnread: true,
    isDraft: false,
    isStarred: true,
  },
  {
    id: 2,
    sender: 'Job Portal System',
    date: 'July 11, 6:30 PM',
    subject: 'Weekly Job Digest - 157 new jobs for you',
    preview: 'Check out latest jobs based on your profile: TCS, Cognizant, Central Govt roles...',
    type: 'Jobs',
    isUnread: false,
    isDraft: false,
    isStarred: false,
  },
  {
    id: 3,
    sender: 'HCL Recruitment Team',
    date: 'July 10, 10:15 AM',
    subject: 'Interview Schedule - Software Developer Role',
    preview: 'Your technical interview is scheduled on July 14 at 11:00 AM IST. Join link inside.',
    type: 'Interview',
    isUnread: true,
    isDraft: false,
    isStarred: false,
  },
  {
    id: 4,
    sender: 'Draft Application',
    date: 'July 9, 3:00 PM',
    subject: 'Draft: Application for Full Stack Developer at Tech Mahindra',
    preview: 'Dear HR, I am excited to apply for the Full Stack Developer position...',
    type: 'Drafts',
    isUnread: false,
    isDraft: true,
    isStarred: false,
  },
  {
    id: 5,
    sender: 'Job Portal System',
    date: 'July 8, 8:00 AM',
    subject: 'Reminder: Complete your profile to get better job matches',
    preview: 'Almost there! Completing your profile improves job recommendations by 80%.',
    type: 'System',
    isUnread: true,
    isDraft: false,
    isStarred: false,
  },
  {
    id: 6,
    sender: 'Accenture HR',
    date: 'July 7, 5:30 PM',
    subject: 'Offer Letter Issued - Digital Associate',
    preview: 'We are pleased to offer you the role of Digital Associate. Please find attached...',
    type: 'Jobs',
    isUnread: false,
    isDraft: false,
    isStarred: true,
  },
  {
    id: 7,
    sender: 'Job Portal System',
    date: 'July 6, 1:15 PM',
    subject: 'Application Update: Cognizant - Frontend Developer',
    preview: 'Your application is being reviewed. We’ll update you once shortlisted.',
    type: 'Jobs',
    isUnread: false,
    isDraft: false,
    isStarred: false,
  },
];
